### ISSUE TITLE
Include sdf-csg in Curated Code CAD?

### ISSUE THREAD

**Issue by Irev-Dev** [wwwtyro/sdf-csg#1]
Really cool project, good readme too 😁 

I maintain a list of "CodeCAD" or programable CAD projects at: [Curated Code CAD](https://learn.cadhub.xyz/blog/curated-code-cad)

Would you like me to include this repo as well? and if so as far as a description goes shoud I just use

> Generate meshes from signed distance functions and constructive solid geometry operations. This library is heavily based upon Inigo Quilez's 3D SDFs article.

Or would you like to give me something different?

I'm also curious how long you've been working on this?

Since this is not a issue directly related to your repo I'll close this issue soon.

**Comment by wwwtyro** [comment]
Thanks, for sure feel free to include it on your list, that would be neat! That description sounds good to me. I put this together in a little less than a week, but all of the hard stuff was done by Inigo Quilez already, and a little bit by me previously for the meshing algorithm.

**Comment by Irev-Dev** [comment]
Sorry, it took me a while to get back to this.

It's been added 🙌 

Super impressive how quick you were able to knock this together even if you were following on from Quilez.
